# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: #pip install -U tox-travis
- pip install matplotlib
- pip install coveralls
- python setup.py install
- pip install tensorflow
- pip install coverage
- pip install scipy

before install:
- pip install -U pip
- export PYTHONPATH=$PYTHONPATH:$(pwd)
- sudo apt-get install -qq python-numpy python-scipy python-matplotlib

# Command to run tests, e.g. python setup.py test
script: #tox

- coverage run --source=schrodingerseqn1d setup.py test
- coverage report -m

after_success: coveralls

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: raickhr
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: raickhr/schrodingerseqn1d
    python: 3.6
